version: '3'

services:
  db:
    image: postgres:11.5
    container_name: db
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    volumes:
      - ./dbData:/var/lib/postgresql/data
      
  backup:
    build:
      context: .
      args:
        ALPINE_VERSION: '3.16'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      SCHEDULE: '@weekly'     # optional
      BACKUP_KEEP_DAYS: 52     # optional
      PASSPHRASE: ${AWS_BACKUP_ENCRYPTION_KEY}  # optional
      S3_REGION: ${AWS_BACKUP_S3_BUCKET_REGION}
      S3_ACCESS_KEY_ID: ${AWS_BACKUP_ACCESS_KEY}
      S3_SECRET_ACCESS_KEY: ${AWS_BACKUP_SECRET_ACCESS_KEY}
      S3_BUCKET: ${AWS_BACKUP_S3_BUCKET_NAME}
      S3_PREFIX: backups
      POSTGRES_HOST: ${POSTGRES_DB_HOST}
      POSTGRES_DATABASE: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    extra_hosts:
      - "host.docker.internal:172.17.0.1"